### ISSUE TITLE
French accented/special characters aren't showing up properly

### ISSUE THREAD

**Issue by evanlws12** [evanlws12/Bicycle-Rental-System#24]

**Comment by zbear1** [comment]
I may have figured out what is going on here.  I am going to try to fix it.

**Comment by zbear1** [comment]
The problem was with the properties file.  For some reason instead of using Unicode, properties files store text as ISO-8859-1.  So I used native2ascii.com to convert the special characters into their Unicode equivalent.  I will upload the fixed properties file after I am done with making all of the changes.  So this can be closed.

**Comment by evanlws12** [comment]
Okay that was a lot simpler than I thought it would be. @jlapl1 see if there is any other issue you'd like to work on then.
